"""Added Thread Table sync with Doc

Revision ID: 383a803ad070
Revises: 9603b478f1da
Create Date: 2026-05-07 22:51:07.334195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '383a803ad070'
down_revision: Union[str, Sequence[str], None] = '9603b478f1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('docs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('docs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'created_at')
    op.drop_column('docs', 'updated_at')
    op.drop_table('threads')
    # ### end Alembic commands ###
